#!/usr/bin/env bash
#
# bootstrap installs things.

DOTFILES_ROOT="`pwd`"
cd $DOTFILES_ROOT

set -e

echo ''

info () {
  printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

link_files () {
  ln -s $1 $2
  success "linked $1 to $2"
}

install_dotfiles () {
  info 'installing dotfiles'

  overwrite_all=false
  backup_all=false
  skip_all=false

  for source in `find $DOTFILES_ROOT -maxdepth 2 -name \*.symlink`
  do
    dest="$HOME/.`basename \"${source%.*}\"`"

    if [ -f $dest ] || [ -d $dest ] || [ -h $dest ]
    then

      overwrite=false
      backup=false
      skip=false

      if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
      then
        user "File already exists: `basename $source`, what do you want to do? [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac
      fi

      if [ "$overwrite" == "true" ] || [ "$overwrite_all" == "true" ]
      then
        rm -rf $dest
        success "removed $dest"
      fi

      if [ "$backup" == "true" ] || [ "$backup_all" == "true" ]
      then
        mv $dest $dest\.backup
        success "moved $dest to $dest.backup"
      fi

      if [ "$skip" == "false" ] && [ "$skip_all" == "false" ]
      then
        link_files $source $dest
      else
        success "skipped $source"
      fi

    else
      link_files $source $dest
    fi
  done
}

create_dropbox_links () {
  DROPBOX=${HOME}/Dropbox/
  SSHCONF_DEST=${HOME}/.ssh/config
  SSHCONF_SRC=${DROPBOX}/symlinks/ssh_config
  DOTJS=${DROPBOX}/symlinks/dotjs

  if [[ -h ~/.js ]]; then
    success "Link ~/.js exists"
  elif [[ -d  ~/.js ]]; then
    fail "Directory ~/.js exists"
  else
    ln -s ${DOTJS} ~/.js
    success "linked ~/.js"
  fi

  if [[ -e ${SSHCONF_SRC} ]]; then
    if [[ -e ${SSHCONF_DEST} ]]; then
      mv ${SSHCONF_DEST} ${SSHCONF_DEST}.backup
      success "moved ${SSHCONF_DEST} to ${SSHCONF_DEST}.backup"
    fi
    link_files ${SSHCONF_SRC} ${SSHCONF_DEST}
    chmod 600 ${SSHCONF_DEST}
  fi
}

install_dotfiles
create_dropbox_links

echo
echo '  All installed!'
echo

source ~/.bash_profile
