#!/usr/bin/env bash
#
# bootstrap installs things.

if [[ "$(whoami)" != "root" ]]; then
    echo "Please run me as root"
    exit
fi

DOTFILES_ROOT="`pwd`"
cd $DOTFILES_ROOT

set -e

echo ''

info () {
  printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

link_files () {
  ln -s $1 $2
  success "linked $1 to $2"
}

install_dotfiles () {
  info 'installing dotfiles'

  overwrite_all=false
  backup_all=false
  skip_all=false

  for source in `find $DOTFILES_ROOT -maxdepth 2 -name \*.symlink`
  do
    dest="$HOME/.`basename \"${source%.*}\"`"

    if [ -f $dest ] || [ -d $dest ] || [ -h $dest ]
    then

      overwrite=false
      backup=false
      skip=false

      if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
      then
        user "File already exists: `basename $source`, what do you want to do? [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac
      fi

      if [ "$overwrite" == "true" ] || [ "$overwrite_all" == "true" ]
      then
        rm -rf $dest
        success "removed $dest"
      fi

      if [ "$backup" == "true" ] || [ "$backup_all" == "true" ]
      then
        mv $dest $dest\.backup
        success "moved $dest to $dest.backup"
      fi

      if [ "$skip" == "false" ] && [ "$skip_all" == "false" ]
      then
        link_files $source $dest
      else
        success "skipped $source"
      fi

    else
      link_files $source $dest
    fi
  done
}

install_programs() {
  info 'installing programs'
  echo ''
  apt-get -qq update
  apt-get -yqq install rsync curl vim git-core screen htop vnstat colordiff xclip python-pip
  echo ''
  success 'installed'

  info "installing pip requirements"
  echo ''
  pip install -qr pip/requirements.txt
  echo ''
  success "pip requirements installed"

  if [[ ! -d $HOME/src/z/ ]]; then
    info "downloading z"
    mkdir -p $HOME/src/z
    curl https://raw.github.com/rupa/z/master/z.sh > $HOME/src/z/z.sh
    chmod +x $HOME/src/z/z.sh
    success "z installed"
  fi

}

create_dropbox_links () {
  DROPBOX=$HOME/Dropbox
  SSH_CONFIG=$HOME/.ssh/config
  SSH_CONFIG_DB=$DROPBOX/symlinks/ssh_config
  mkdir -p $DROPBOX

  if [[ -e $SSH_CONFIG_DB ]]; then
    info "copying ssh config"
    cp -f $SSH_CONFIG_DB $SSH_CONFIG
    chmod 600 $SSH_CONFIG
    success "ssh config copied"
  fi
}

install_dotfiles
install_programs
create_dropbox_links

echo ''
echo '  All installed!'

source ~/.bash_profile
