#!/bin/bash

srcdir=$HOME/src

export PATH="$PATH:$srcdir/git-achievements"
export PS1="\u@\h\w$ "

#aliases
if [ -d $srcdir/dotfiles/base/ ]; then
  for filename in $(ls $srcdir/dotfiles/base/*); do
    . $filename
  done
fi;

#secret files :)
if [ -d $srcdir/dotfiles/local/ ]; then
  for filename in $(ls $srcdir/dotfiles/local/*); do
    . $filename
  done
fi;

#functions
g(){
  $HOME/bin/sublime/sublime_text $@ &
}

blame(){
  svn blame $@ | less
}

svnlog(){
  svn log -vl 50 | less
}

lint(){
  pylint $@ | less
}

svndi(){
  svn di $@ | colordiff | less -R
}

ttail(){
  tail -f $@ | while read; do echo -e "$(date +%T.%N) $REPLY"; done
}

mktar() { tar cvf  "${1%%/}.tar" "${1%%/}/"; }
mktgz() { tar cvzf "${1%%/}.tgz" "${1%%/}/"; }
